[phases.setup]
nixPkgs = ["python311", "mariadb"]

[phases.install]
cmds = ["pip3 install --upgrade pip", "pip3 install -r requirements.txt"]

[start]
cmd = "gunicorn backend_calories_calc.wsgi:application --bind 0.0.0.0:$PORT"
